config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dynamic#home"
  get 'team', to: 'static#team' 
  get 'contact', to: 'static#contact'
  get 'home/:first_name', to: 'dynamic#home_first_name', as: 'first_name'
  get 'home/gossip/:id', to: 'dynamic#gossip', as: 'gossip'
  get 'home/gossip/user/:id', to: 'dynamic#author', as: 'user'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :tags
    has_many :comments
end

app/models/join_table_tags_gossip.rb
class JoinTableTagsGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
    attr_accessor :gossips, :gossip, :author
    def home_first_name
        @gossips = Gossip.all
    end
    
    def home
        @gossips = Gossip.all
	end
	
    def gossip
        @gossip = Gossip.find_by(id: params[:id])
        @author = User.find_by(id: @gossip.user_id)
    end

    def author 
        @gossip = Gossip.find_by(id: params[:id])
        @author = User.find_by(id: @gossip.user_id)
    end
  end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
    def welcome
    end
  end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dynamic/author.html.erb
<h1>Nom : <%= @author.first_name%></h1>
<h1>Prénom : <%= @author.last_name%></h1>
<h3>Email : <%= @author.email %></h3>
<h3>Age: <%= @author.age %> ans</h3>
<h3>Ville: <%= @author.city.name %></h3>
<h4>Bio : <%= @author.description %></h4>

app/views/dynamic/gossip.html.erb
<h3> Titre : <%= @gossip.title %> </h3>
</br>
<h4> Potin :</h4>
<p> <%= @gossip.content %></p>
<%= link_to "En savoir plus sur l'auteur du potin", user_path(@author.id), class: "btn btn-primary" %>

app/views/dynamic/home.html.erb
<h1 class="text-center">La boîte à ragots ultimes</h1>
<h1 class="text-center">The Gossip Project</h1>


<div class="row">

<% @gossips.each do |gossip| %>
<div class="card col-sm-3 text-center">
  <div class="card-header">
    <p>potin n°<%= gossip.id %></p>
  </div>
  <div class="card-body">
    <h5 class="card-title">Auteur : <%= gossip.user.first_name %></h5>
    <p class="card-text">Titre : <%= gossip.title %></p>
    <%= link_to "En savoir plus", gossip_path(gossip.id), class: "btn btn-primary" %>
  </div>
</div>
<% end %>

</div>

app/views/dynamic/home_first_name.html.erb
<h1 class="text-center"><%= params[:first_name] %>, Bienvenue à Jurassic..</h1>
<h3 class="text-center">euh non me gourre d'endroit..</h3>
<h1 class="text-center">Bienvenue sur The Gossip Project !</h1>

<div class="row">

<% @gossips.each do |gossip| %>
    <div class="card col-sm-3 text-center">
        <div class="card-header">
            <p>potin n°<%= gossip.id %></p>
        </div>
        <div class="card-body">
            <h5 class="card-title">Auteur : <%= gossip.user.first_name %></h5>
            <p class="card-text">Titre : <%= gossip.title %></p>
            <%= link_to "En savoir plus", gossip_path(gossip.id), class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--install BootstrapCDN-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
          <%= link_to "Accueil", root_path, class: "navbar-brand"%>
          <%= link_to "L'équipe", team_path, class: 'nav-link'%>
          <%= link_to "Contact", contact_path, class: 'nav-link'%>
        </div>
      </div>
    </nav>
    <%= yield %>
    
  </body>
</html>